apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appcatalog-helm-stable
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: appcatalog
      sourceRef:
        kind: HelmRepository
        name: giantswarm-control-plane-test-catalog
        namespace: flux-giantswarm
      version: 0.10.1-59cc2b9b85459827bd7f19e2d9dd7e715a1be4f5
  install:
    remediation:
      retries: 20
      remediateLastFailure: False
  interval: 24h
  releaseName: appcatalog-helm-stable
  storageNamespace: giantswarm
  targetNamespace: giantswarm
  timeout: 3m
  upgrade:
    remediation:
      retries: 20
      remediateLastFailure: False
  values:
    appCatalog:
      name: "helm-stable"
      title: "Helm Stable"
      catalogType: "community"
      catalogVisibility: "public"
      description: >
        This is the Helm Stable chart repository that you can find here:
        https://github.com/helm/charts/tree/master/stable
        This App Catalog does not have any guarantees or SLA.
      logoURL: "/images/repo_icons/community.png"
      storage:
        URL: "https://charts.helm.sh/stable/packages/"
