apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patches/konfiguration.yaml
resources:
  - cluster-api-cleaner-vsphere.yaml
  - cluster-api-ipam-provider-in-cluster.yaml
  - cluster-api-provider-vsphere.yaml
  - dns-operator-route53.yaml
  - image-distribution-operator.yaml
