# This is not needed I think
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-gitops-informer-configuration
  namespace: flux-giantswarm
data:
  reconciliationRequestData: "{{ now | unixEpoch }}"
