apiVersion: batch/v1
kind: Job
metadata:
  name: config-change-informer
  namespace: flux-giantswarm
spec:
  # This is important to keep very low or set to 0
  # Problem with 0 is that it is very hard to catch it for debugging
  # Low value is good because than jobs won't collide with each other as `spec.template` is immutable n jobs
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: kubectl
          image: giantswarm/docker-kubectl:1.23.6
          args: ["-n", "flux-giantswarm", "label", "--overwrite", "kustomization", "flux", "reconcile.fluxcd.io/requestedAt={{ now | unixEpoch }}"]
          imagePullPolicy: IfNotPresent
      serviceAccountName: "kustomize-controller"
      restartPolicy: Never
  backoffLimit: 3
