apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rest-api-collection
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-giantswarm-https-credentials
  url: https://github.com/giantswarm/rest-api-app-collection
