apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: konfigure-operator
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: konfigure-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: giantswarm-catalog
        namespace: flux-giantswarm
      version: 0.2.0
  install:
    remediation:
      retries: 10
      remediateLastFailure: false
  interval: 1m
  targetNamespace: giantswarm
  timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: konfigure-operator-values
      valuesKey: values.yaml
