---
apiVersion: v1
kind: ConfigMap
metadata:
  name: konfigure-operator-values
  namespace: flux-giantswarm
data:
  values.yaml: |
    resources:
      limits:
        cpu: 150m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

    verticalPodAutoscaler:
      enabled: true
