apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: giantswarm-control-plane-catalog
        namespace: flux-giantswarm
      version: 2.3.0
  install:
    remediation:
      retries: 10
      remediateLastFailure: False
  interval: 1m
  targetNamespace: crossplane
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: False
  values:
    giantswarm:
      kubernetes:
        provider:
          kind: "replaced in kustomization"
      crossplane:
        providers:
          contribAws:
            enabled: false
    metrics:
      enabled: true
