apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: event-exporter
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: caicloud-event-exporter-app
      sourceRef:
        kind: HelmRepository
        name: giantswarm-control-plane-catalog
        namespace: flux-giantswarm
      version: 0.2.2
  install:
    remediation:
      retries: 10
      remediateLastFailure: False
  interval: 1m
  targetNamespace: crossplane
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: False
  values:
    global:
      podSecurityStandards:
        enforced: ${pssEnforced:=false}
