apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: crossplane
  namespace: flux-giantswarm
spec:
  interval: 1h
  provider: generic
  ref:
    tag: 2.5.1-b191811dc8c641c4daed4a6091c57e03812f75d5 # TODO bump to actual X.Y.Z release (needs new release since we only just enabled pushing to gsoci)
  url: oci://gsoci.azurecr.io/charts/giantswarm/crossplane
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-giantswarm
spec:
  chartRef:
    kind: OCIRepository
    name: crossplane
    namespace: flux-giantswarm
  install:
    remediation:
      retries: 10
      remediateLastFailure: false
  interval: 1m
  targetNamespace: crossplane
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: false
  values:
    metrics:
      enabled: true
    global:
      podSecurityStandards:
        enforced: ${pssEnforced:=true}
