apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: crossplane
  namespace: flux-giantswarm
spec:
  interval: 1h
  provider: generic
  ref:
    # Used by renovate
    # repo: giantswarm/crossplane
    tag: 2.5.2
  url: oci://gsoci.azurecr.io/charts/giantswarm/crossplane
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-giantswarm
spec:
  chartRef:
    kind: OCIRepository
    name: crossplane
    namespace: flux-giantswarm
  install:
    remediation:
      retries: 10
      remediateLastFailure: false
  interval: 1m
  targetNamespace: crossplane
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: false
  values:
    metrics:
      enabled: true
    global:
      podSecurityStandards:
        enforced: true
