apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: giantswarm-control-plane-catalog
        namespace: flux-giantswarm
      version: 2.5.0
  install:
    remediation:
      retries: 10
      remediateLastFailure: false
  interval: 1m
  targetNamespace: crossplane
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: false
  values:
    metrics:
      enabled: true
    global:
      podSecurityStandards:
        enforced: ${pssEnforced:=true}
