apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
  name: crossplane
  namespace: crossplane
spec:
  namespaceSelector:
    matchNames:
      - 'crossplane'
  selector:
    matchLabels:
      app.kubernetes.io/name: crossplane
  podMetricsEndpoints:
    - targetPort: metrics
