apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
  name: crossplane
  namespace: crossplane
spec:
  namespaceSelector:
    matchNames:
      - 'crossplane'
  selector:
    # All pods in the namespace are covered (includes Crossplane provider pods)`
    matchLabels: {}
  podMetricsEndpoints:
    - targetPort: metrics
