apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: backstage
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: giantswarm-control-plane-catalog
        namespace: flux-giantswarm
      version: 0.9.0
  install:
    remediation:
      retries: 10
      remediateLastFailure: false
  interval: 1m
  targetNamespace: backstage
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: false
