---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: backstage-values
  namespace: flux-giantswarm
spec:
  dependsOn:
    - name: flux
      namespace: flux-giantswarm
  interval: 5m
  # IMPORTANT: The `backstage-values` folder must be created and include
  # ConfigMap and Secrets referenced in HelmRelease `spec.valuesFrom` property.
  #
  # DO NOT use slashes in the comment to indicate the path, just "->".
  path: "./management-clusters/{replaced in management-clusters -> <MC_NAME> -> kustomization.yaml}/backstage-values"
  prune: false
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: management-clusters-fleet
    namespace: flux-giantswarm
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
