apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1beta2
      kind: 'GitRepository'
      name: '.*'
      namespace: 'flux-giantswarm'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: source.toolkit.fluxcd.io/v1
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1beta2
      kind: 'Kustomization'
      name: '.*'
      namespace: 'flux-giantswarm'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: kustomize.toolkit.fluxcd.io/v1
  - target:
      kind: GitRepository
      name: collection
      namespace: flux-giantswarm
    patch: |-
      - op: replace
        path: /spec/ref/branch
        value: main
replacements:
  # Points collection GitRepository to correct URL
  - source:
      kind: ConfigMap
      name: provider-data
      fieldPath: data.collection_url
    targets:
      - select:
          kind: GitRepository
          name: collection
          namespace: flux-giantswarm
        fieldPaths:
          - spec.url
resources:
  - ../../../flux-app-v2/customer
  - ../../../flux-app-v2/giantswarm
  - ../../../flux-giantswarm-resources
  - configmap-provider-data.yaml
