apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: collection
  namespace: flux-giantswarm
spec:
  ref:
    branch: bootstrap-clusters-k8sv1.25
  url: https://github.com/giantswarm/vsphere-app-collection
