---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: upbound-provider-gcp
  namespace: crossplane
spec:
  args:
    - --debug
  image: docker.io/giantswarm/upbound-provider-gcp:v0.33.0
  serviceAccountName: upbound-provider-gcp
