---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-gcp
  namespace: crossplane
  labels:
    provider-family: gcp
    provider-family-member: gcp-family
spec:
  ignoreCrossplaneConstraints: false
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
  package: xpkg.upbound.io/upbound/provider-family-gcp:v${gcpversion:=0.38.0}
  runtimeConfigRef:
    name: upbound-provider-family-gcp
