apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: collection
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: github-giantswarm-https-credentials
  timeout: 5m
  url: https://github.com/giantswarm/aws-app-collection
