apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patch-helm-controller.yaml
  - path: patch-kustomize-controller.yaml
  - path: patch-source-controller.yaml
  - path: patch-collection-gitrepository.yaml
images:
  - name: giantswarm/fluxcd-helm-controller
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/fluxcd-helm-controller
  - name: giantswarm/fluxcd-image-automation-controller
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/fluxcd-image-automation-controller
  - name: giantswarm/fluxcd-image-reflector-controller
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/fluxcd-image-reflector-controller
  - name: giantswarm/fluxcd-notification-controller
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/fluxcd-notification-controller
  - name: giantswarm/fluxcd-source-controller
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/fluxcd-source-controller
  - name: giantswarm/kustomize-controller
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/kustomize-controller
  - name: giantswarm/k8s-jwt-to-vault-token
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/k8s-jwt-to-vault-token
  - name: giantswarm/konfigure
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/konfigure
  - name: giantswarm/docker-kubectl
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/docker-kubectl
  - name: giantswarm/alpine-helm
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/alpine-helm
  - name: giantswarm/external-secrets
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/external-secrets
  - name: giantswarm/fluxcd-kustomize-controller
    newName: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/fluxcd-kustomize-controller
resources:
  - ../../../flux-app-v2/giantswarm
  - ../../../flux-giantswarm-resources
  - configmap-provider-data.yaml
