apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-giantswarm
spec:
  template:
    spec:
      hostAliases:
      - ip: "192.168.190.101"
        hostnames:
        - "giantswarm.github.io"
