apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-giantswarm
spec:
  template:
    spec:
      hostAliases:
      - ip: "192.168.190.100"
        hostnames:
          - "github.com"
      - ip: "192.168.190.102"
        hostnames:
        - "ssh.github.com"
