apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-app
  namespace: org-sample
spec:
  interval: 5m
  provider: generic
  ref:
    tag: "4.0.1"
  url: oci://gsoci.azurecr.io/charts/giantswarm/cert-manager-app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sample-customer-cert-manager
  namespace: org-sample
spec:
  releaseName: cert-manager
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chartRef:
    kind: OCIRepository
    name: cert-manager-app
    namespace: org-sample
  interval: 50m
  install:
    remediation:
      retries: 3
