apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: gateway-api-bundle
    app-operator.giantswarm.io/version: 0.0.0
  name: gateway-api-bundle
  namespace: org-giantswarm
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: true
  name: gateway-api-bundle
  namespace: org-giantswarm
  userConfig:
    configMap:
      name: gateway-api-bundle-base
      namespace: org-giantswarm
  version: 0.3.0
