---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-acm
  namespace: crossplane
spec:
  ignoreCrossplaneConstraints: false
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: true
  package: gsoci.azurecr.io/giantswarm/upbound-provider-aws-acm:v${awsversion:=1.21.0}
  runtimeConfigRef:
    name: upbound-provider-aws
