---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: upbound-provider-aws
  namespace: crossplane
spec:
  args:
    - --debug
    - --max-reconcile-rate=100
  image: docker.io/giantswarm/upbound-provider-aws:v0.30.0
  serviceAccountName: upbound-provider-aws
