---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws
  namespace: crossplane
spec:
  controllerConfigRef:
    name: upbound-provider-aws
  ignoreCrossplaneConstraints: false
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
