---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-aws
  namespace: crossplane
  labels:
    provider-family: aws
    provider-family-member: aws-family
spec:
  ignoreCrossplaneConstraints: false
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: true
  package: gsoci.azurecr.io/giantswarm/upbound-provider-family-aws:v1.21.0
  runtimeConfigRef:
    name: upbound-provider-family-aws
