---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: replaced by kustomization
  namespace: crossplane
  annotations: {}
  labels:
    provider-family: aws
    provider-family-member: aws-provider

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: upbound-provider-family-aws
  namespace: crossplane
  annotations: {}
  labels:
    provider-family: aws
    provider-family-member: aws-family

---
# Create the service account to be used for network discovery
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xfn-network-discovery
  namespace: crossplane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xfn-aws-provider-config-access
rules:
  - apiGroups:
      - aws.upbound.io
    resources:
      - providerconfigs
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xfn-aws-provider-config-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xfn-aws-provider-config-access
subjects:
  - kind: ServiceAccount
    name: xfn-network-discovery
    namespace: crossplane
