apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kratix
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: kratix
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: giantswarm-test-catalog
        namespace: flux-giantswarm
      version: 0.1.0
  install:
    remediation:
      retries: 10
      remediateLastFailure: false
  interval: 1m
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: false
  #  valuesFrom:
  #    - kind: ConfigMap
  #      name: zot-cache-values
  #      valuesKey: values.yaml
