apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auto-ready.yaml
  - kcl.yaml
  - patch-and-transform.yaml
  # Does not really belong here, but must be deployed after providers.
  - providerconfig.yaml
