apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: podinfo
  namespace: org-sample
spec:
  interval: 5m
  provider: generic
  ref:
    semver: ">=6.0.0"
  url: oci://ghcr.io/stefanprodan/charts/podinfo
