apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patches/konfiguration.yaml
resources:
  - cluster-api-cleaner-cloud-director.yaml
  - cluster-api-provider-cloud-director.yaml
  - dns-operator-route53.yaml
  - image-distribution-operator.yaml
