---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: upbound-provider-azure
  namespace: crossplane
spec:
  args:
    - --debug
  serviceAccountName: upbound-provider
  metadata:
    annotations: {}
    labels: {}
