---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-azure
  namespace: crossplane
spec:
  controllerConfigRef:
    name: upbound-provider-azure
  ignoreCrossplaneConstraints: false
  package: xpkg.upbound.io/upbound/provider-azure:v0.31.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
