---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-azure
  namespace: crossplane
  labels:
    provider-family: azure
    provider-family-member: azure-family
spec:
  ignoreCrossplaneConstraints: false
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: true
  package: gsoci.azurecr.io/giantswarm/upbound-provider-family-azure:v${azureversion:=1.0.0}
  runtimeConfigRef:
    name: upbound-provider-family-azure
