---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: upbound-provider-azure
  namespace: crossplane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-use-psp-upbound-provider-azure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-use-psp
subjects:
- kind: ServiceAccount
  name: upbound-provider-azure
  namespace: crossplane
