$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: refresh-vault-token
  namespace: flux-giantswarm
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["*"]