$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: refresh-vault-token
  namespace: flux-giantswarm
subjects:
  - kind: ServiceAccount
    name: refresh-vault-token
    namespace: flux-giantswarm
roleRef:
  kind: Role
  name: refresh-vault-token
  apiGroup: rbac.authorization.k8s.io