apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: releases
  namespace: flux-giantswarm
spec:
  sourceRef:
    kind: GitRepository
    name: releases
    namespace: flux-giantswarm
  prune: true
  interval: 1m
