apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appcatalog-control-plane-test-catalog
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: appcatalog
      sourceRef:
        kind: HelmRepository
        name: giantswarm-control-plane-catalog
        namespace: flux-giantswarm
      version: 0.10.1
  install:
    remediation:
      retries: 20
      remediateLastFailure: False
  interval: 24h
  releaseName: appcatalog-control-plane-test-catalog
  storageNamespace: giantswarm
  targetNamespace: giantswarm
  timeout: 3m
  upgrade:
    remediation:
      retries: 20
      remediateLastFailure: False
  values:
    appCatalog:
      name: "control-plane-test-catalog"
      title: "Control Plane Test Catalog"
      catalogType: "test"
      catalogVisibility: "internal"
      description: >
        This catalog holds test Apps exclusively running on Giant Swarm control planes.
      logoURL: "/images/repo_icons/giantswarm.png"
      storage:
        URL: "https://giantswarm.github.io/control-plane-test-catalog/"
      repositories:
        - type: oci
          URL: "oci://giantswarmpublic.azurecr.io/control-plane-test-catalog/"
      config:
        configMap:
          name: "draughtsman-values-configmap"
          namespace: "draughtsman"
          managed: false
        secret:
          name: "draughtsman-values-secret"
          namespace: "draughtsman"
          managed: false
