apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patch-collection-gitrepository.yaml
resources:
  - ../../../flux-app-v2/giantswarm
  - ../../../flux-giantswarm-resources
  - ../releases
  - configmap-provider-data.yaml
