resources:
  - https://raw.githubusercontent.com/giantswarm/observability-operator/refs/tags/v0.68.0/config/crd/bases/observability.giantswarm.io_agentcredentials.yaml
  - https://raw.githubusercontent.com/giantswarm/observability-operator/refs/tags/v0.68.0/config/crd/bases/observability.giantswarm.io_grafanaorganizations.yaml
