---
apiVersion: konfigure.giantswarm.io/v1alpha1
kind: Konfiguration
metadata:
  name: vsphere-addons-collection-konfiguration
  namespace: giantswarm
spec:
  targets:
    schema:
      reference:
        name: management-cluster-configuration
        namespace: giantswarm
    defaults:
      variables:
        - name: installation
          value: "${cluster_name}"
    iterations:
      cluster-api-cleaner-vsphere:
        variables:
          - name: app
            value: cluster-api-cleaner-vsphere
          - name: team
            value: rocket
      cluster-api-ipam-provider-in-cluster:
        variables:
          - name: app
            value: cluster-api-ipam-provider-in-cluster
          - name: team
            value: rocket
      cluster-api-provider-vsphere:
        variables:
          - name: app
            value: cluster-api-provider-vsphere
          - name: team
            value: rocket
      image-distribution-operator:
        variables:
          - name: app
            value: image-distribution-operator
          - name: team
            value: rocket
  destination:
    namespace: giantswarm
    naming:
      suffix: konfiguration
      useSeparator: true
  reconciliation:
    interval: 1m
    retryInterval: 30s
    suspend: false
  sources:
    flux:
      gitRepository:
        name: "giantswarm-config"
        namespace: "flux-giantswarm"
