---
apiVersion: konfigure.giantswarm.io/v1alpha1
kind: Konfiguration
metadata:
  name: CHANGE_ME
  namespace: giantswarm
spec:
  targets:
    schema:
      reference:
        name: management-cluster-configuration
        namespace: giantswarm
    defaults:
      variables:
        - name: installation
          value: "${cluster_name}"
    iterations:
      cluster-api-cleaner-vsphere:
        variables:
          - name: app
            value: cluster-api-cleaner-vsphere
      cluster-api-ipam-provider-in-cluster:
        variables:
          - name: app
            value: cluster-api-ipam-provider-in-cluster
      cluster-api-provider-vsphere:
        variables:
          - name: app
            value: cluster-api-provider-vsphere
      image-distribution-operator:
        variables:
          - name: app
            value: image-distribution-operator
      konfiguration:
        variables:
          - name: app
            value: konfiguration
      kustomization:
        variables:
          - name: app
            value: kustomization
  destination:
    namespace: giantswarm
    naming:
      suffix: konfiguration
      useSeparator: true
  reconciliation:
    interval: 1m
    retryInterval: 10s
    suspend: false
  sources:
    flux:
      gitRepository:
        name: "giantswarm-config"
        namespace: "flux-giantswarm"
