apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-customer-fluent-logshipping-app
  namespace: org-sample
spec:
  releaseName: fluent-logshipping-app
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chart:
    spec:
      chart: fluent-logshipping-app
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: giantswarm-catalog
        namespace: default
  interval: 50m
  install:
    remediation:
      retries: 3
