apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appcatalog-cluster-releases
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: appcatalog
      sourceRef:
        kind: HelmRepository
        name: giantswarm-control-plane-catalog
        namespace: flux-giantswarm
      version: 1.0.0
  install:
    remediation:
      retries: 20
      remediateLastFailure: False
  interval: 24h
  releaseName: appcatalog-cluster-releases
  storageNamespace: giantswarm
  targetNamespace: giantswarm
  timeout: 3m
  upgrade:
    remediation:
      retries: 20
      remediateLastFailure: False
  values:
    appCatalog:
      name: "cluster-releases"
      title: "Giant Swarm Cluster Releases Catalog"
      catalogType: "stable"
      catalogVisibility: "public"
      catalogNamespace: "giantswarm"
      description: "This catalog holds release-versioned cluster provider charts for automated cluster upgrades."
      logoURL: "/images/repo_icons/giantswarm.png"
      storage:
        URL: "oci://giantswarmpublic.azurecr.io/cluster-releases-catalog/"
      repositories:
        - type: oci
          URL: "oci://giantswarmpublic.azurecr.io/cluster-releases-catalog/"
