apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: appcatalog-giantswarm-test
  namespace: flux-giantswarm
spec:
  chartRef:
    kind: OCIRepository
    name: appcatalog
    namespace: flux-giantswarm
  install:
    remediation:
      retries: 20
      remediateLastFailure: False
  interval: 24h
  releaseName: appcatalog-giantswarm-test
  storageNamespace: giantswarm
  targetNamespace: giantswarm
  timeout: 3m
  upgrade:
    remediation:
      retries: 20
      remediateLastFailure: False
  values:
    appCatalog:
      name: "giantswarm-test"
      title: "Giant Swarm Test"
      catalogType: "test"
      catalogVisibility: "internal"
      description: "This catalog holds test versions of the apps in Giant Swarm. No guarantees, no SLA! Here be dragons! Giant Swarm developers only."
      logoURL: "/images/repo_icons/incubator.png"
      storage:
        URL: "https://giantswarm.github.io/giantswarm-test-catalog/"
      repositories:
        - type: oci
          URL: "oci://gsoci.azurecr.io/charts/giantswarm/"
