apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appcatalog-giantswarm
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: appcatalog
      sourceRef:
        kind: HelmRepository
        name: giantswarm-control-plane-test-catalog
        namespace: flux-giantswarm
      version: 0.10.1-59cc2b9b85459827bd7f19e2d9dd7e715a1be4f5
  install:
    remediation:
      retries: 20
      remediateLastFailure: False
  interval: 24h
  releaseName: appcatalog-giantswarm
  storageNamespace: giantswarm
  targetNamespace: giantswarm
  timeout: 3m
  upgrade:
    remediation:
      retries: 20
      remediateLastFailure: False
  values:
    appCatalog:
      name: "giantswarm"
      title: "Giant Swarm Catalog"
      catalogType: "stable"
      catalogVisibility: "public"
      description: >
        This catalog holds Apps managed by Giant Swarm.
      logoURL: "/images/repo_icons/managed.png"
      storage:
        URL: "https://giantswarm.github.io/giantswarm-catalog/"
      repositories:
        - type: oci
          URL: "oci://giantswarmpublic.azurecr.io/giantswarm-catalog/"
