patches:
  - target:
      kind: Konfiguration
      name: collection-konfiguration
      namespace: giantswarm
    patch: '[{"op": "add", "path": "/spec/targets/defaults/variables/-", "value": {"name": "stage", "value": "testing"}}]'
  - target:
      kind: OCIRepository
      name: konfigure-operator
      namespace: giantswarm
    patch: '[{"op": "replace", "path": "/spec/ref/semver", "value": "1.1.0-8c66b39ca967addc2827e06883c99ad704f9f78d"}]'
resources:
  - ../../base
