apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
  namespace: org-sample
spec:
  interval: 5m
  provider: generic
  ref:
    tag: "2.38.0"
  url: oci://gsoci.azurecr.io/charts/giantswarm/grafana
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sample-customer-grafana
  namespace: org-sample
spec:
  releaseName: grafana
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chartRef:
    kind: OCIRepository
    name: grafana
    namespace: org-sample
  interval: 50m
  install:
    remediation:
      retries: 3
