apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sample-customer-ingress-nginx
  namespace: org-sample
spec:
  releaseName: ingress-nginx
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chart:
    spec:
      chart: ingress-nginx
      version: '3.2.1'
      sourceRef:
        kind: HelmRepository
        name: giantswarm-catalog
        namespace: default
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    baseDomain: sample-customer.gaws.gigantic.io
    provider: capa
