---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: konfigure-operator
  namespace: giantswarm
spec:
  interval: 10m
  provider: generic
  ref:
    semver: x.x.x
  url: oci://gsoci.azurecr.io/charts/giantswarm/konfigure-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konfigure-operator
  namespace: giantswarm
spec:
  chartRef:
    kind: OCIRepository
    name: konfigure-operator
    namespace: giantswarm
  install:
    remediation:
      remediateLastFailure: false
      retries: 10
  interval: 5m
  releaseName: konfigure-operator
  storageNamespace: giantswarm
  targetNamespace: giantswarm
  timeout: 10m
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 10
      strategy: rollback
  valuesFrom:
  - kind: ConfigMap
    name: konfigure-operator-konfiguration
    valuesKey: configmap-values.yaml
  - kind: Secret
    name: konfigure-operator-konfiguration
    valuesKey: secret-values.yaml
