---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: gsoci.azurecr.io/giantswarm/crossplane-contrib-function-patch-and-transform:v0.6.0
  skipDependencyResolution: true
