apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: deploymentnotsatisfiedatlas
  namespace: monitoring
  annotations:
    motivation: Observability-operator upgrade may generate temporary alerts
    valid-until: 2026-04-28
spec:
  matchers:
    - name: alertname
      value: "DeploymentNotSatisfiedAtlas"
      matchType: "="
    - name: cluster_id
      value: ".*"
      matchType: "=~"
