apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: atlas-mimirhelmreleasefailed
  annotations:
    motivation: Under investigation, no point in paging continuously
    valid-until: "2026-03-30"
  namespace: monitoring
spec:
  matchers:
    - name: alertname
      value: FluxHelmReleaseFailed
      matchType: "="
    - name: cluster_id
      value: ".*"
      matchType: "=~"
