apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: jobscrapingfailure
  annotations:
    motivation: Trying to figure out what to do with this alert.
    github_issue: https://github.com/giantswarm/giantswarm/issues/26963
    valid-until: "2025-09-23"
  namespace: kube-system
spec:
  matchers:
    - name: alertname
      value: JobScrapingFailure
      matchType: "="
    - name: cluster_id
      value: ".*"
      matchType: "=~"
