apiVersion: monitoring.giantswarm.io/v1alpha1
kind: Silence
metadata:
  name: test-silence-for-workflow
  annotations:
    motivation: "This is a test silence created to verify the expiration workflow"
    valid-until: "2025-05-16"
spec:
  matchers:
    - name: alertname
      value: TestAlertForSilence
      isRegex: false
