apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: kedaerrors
  annotations:
    motivation: We don't support keda yet, yet some customers-installed keda are alerting.
    valid-until: "2025-07-29"
spec:
  matchers:
    - name: alertname
      value: KedaScale.*
      matchType: "=~"
    - name: cluster_id
      value: ".*"
      matchType: "=~"
