apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: giantswarm-catalog
        namespace: flux-giantswarm
      version: 0.18.3
  install:
    remediation:
      retries: 10
      remediateLastFailure: False
  interval: 1m
  targetNamespace: external-secrets
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: False
  values:
    giantswarm:
      policyExceptionNamespace: "giantswarm"
      crds:
        install: true
        resources:
          requests:
            memory: "1000Mi"
            cpu: "250m"
          limits:
            memory: "1500Mi"
            cpu: "500m"
