apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
  name: external-secrets
  namespace: external-secrets
spec:
  namespaceSelector:
    matchNames:
      - 'external-secrets'
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
  name: external-secrets-webhook
  namespace: external-secrets
spec:
  namespaceSelector:
    matchNames:
      - 'external-secrets'
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    application.giantswarm.io/team: honeybadger
  name: external-secrets-cert-controller
  namespace: external-secrets
spec:
  namespaceSelector:
    matchNames:
      - 'external-secrets'
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-cert-controller
  podMetricsEndpoints:
    - port: metrics
