apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: team-stamper
  namespace: flux-giantswarm
spec:
  chartRef:
    kind: OCIRepository
    name: team-stamper
    namespace: flux-giantswarm
  install:
    remediation:
      retries: 3
      remediateLastFailure: false
  interval: 10m
  targetNamespace: flux-giantswarm
  timeout: 10m
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: false
