apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: team-stamper
  namespace: giantswarm
spec:
  interval: 10m
  url: oci://gsoci.azurecr.io/charts/giantswarm/team-stamper
  ref:
    tag: 0.0.0-5888446bd27bd03ab1bcb5555ae4712f69725aa3
  provider: generic
