apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: team-stamper
  namespace: flux-giantswarm
spec:
  interval: 10m
  url: oci://gsoci.azurecr.io/charts/giantswarm/team-stamper
  ref:
    tag: 0.0.0-a23febf69ffc8e921999674754a2f9860a5a4270
  provider: generic
