apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches: []
resources:
  - aws-lb-controller-bundle.yaml
  - aws-resolver-rules-operator.yaml
  - aws-vpc-operator.yaml
  - capa-iam-operator.yaml
  - object-storage-operator.yaml
