apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-giantswarm
spec:
  template:
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "ssh.github.com"
