apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: management-clusters-fleet
  namespace: flux-giantswarm
spec:
  secretRef:
    name: giantswarm-clusters-ssh-credentials
  url: ssh://github.com:443/giantswarm/${customer_codename}-management-clusters.git
