apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    name: zot-config
    fieldPath: metadata.name
  targets:
  - select:
      kind: HelmRelease
    fieldPaths:
      - spec.valuesFrom.[name=__VALUES_CM_NAME__].name

resources:
  - ./namespace.yaml
  - ./helm-release.yaml

configMapGenerator:
- name: zot-config
  namespace: zot
  files:
  - ./values.yaml
