apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-loki
  name: hello-loki
  namespace: monitoring
spec:
  clusterIP: None
  selector:
    app: hello
  type: ClusterIP
status:
  loadBalancer: {}
