---
apiVersion: v1
data:
  loki-user-values: |
    global:
        dnsService: coredns
        clusterDomain: cluster.local
    multiTenantAuth:
      enabled: true
      # Credentials will come from secret user values
    giantswarm:
      labelmonitoring:
        enabled: false
    loki:
      monitoring:
        serviceMonitor:
          enabled: true
      loki:
        compactor:
          retention_enabled: true
        limits_config:
          retention_period: 744h  # 744d = 31d
        schemaConfig:
          configs:
            - from: '2020-09-07'
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: loki_index_
                period: 24h
            - from: '2023-01-24'
              store: boltdb-shipper
              object_store: s3
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
        storage:
          type: s3
          bucketNames:
            chunks: gauss-g8s-loki
            ruler: gauss-g8s-loki
            admin: gauss-g8s-loki
          s3:
            region: eu-west-1
      gateway:
        nginxConfig:
          customReadUrl: http://loki-multi-tenant-proxy.loki.svc.cluster.local:3100
          customWriteUrl: http://loki-multi-tenant-proxy.loki.svc.cluster.local:3101
          customBackendUrl: http://loki-multi-tenant-proxy.loki.svc.cluster.local:3102
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-giantswarm
          hosts:
            - host: loki.g8s.gauss.eu-west-1.aws.gigantic.io
              paths:
                - path: /loki/api/v1/push
                  pathType: ImplementationSpecific
          tls:
            - hosts:
              - loki.g8s.gauss.eu-west-1.aws.gigantic.io
              secretName: loki-ingress-cert
kind: ConfigMap
metadata:
  name: loki-user-values
  namespace: giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: loki
  name: loki
  namespace: giantswarm
spec:
  catalog: giantswarm
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: loki
  namespace: loki
  userConfig:
    configMap:
      name: loki-user-values
      namespace: giantswarm
    secret:
      name: ""
      namespace: ""
  version: 0.9.0
