patches:
  - target:
      kind: ClusterPolicy
      name: argo-cluster-secret-generation
    patch: |-
      - op: replace
        path: /spec/rules/0/context/4/apiCall/urlPath
        value: "/api/v1/namespaces/{{request.object.metadata.namespace}}/secrets/{{kubeconfigName}}"
resources:
  - ../kyverno
