apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../flux-app-v2/customer
  - ../../../flux-app-v2/giantswarm
  - ../../../flux-giantswarm-resources
  - collection-gitrepository.yaml
  - configmap-provider-data.yaml
