apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: collection
  namespace: flux-giantswarm
spec:
  url: https://github.com/giantswarm/aws-app-collection
  ref:
    branch: vintage
