{{ if eq (include "resource.vpa.enabled" .) "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: helm-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: {{ .Values.resources.helmController.requests.cpu }}
        memory: {{ .Values.resources.helmController.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.resources.helmController.limits.cpu }}
        memory: {{ .Values.resources.helmController.limits.memory }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  helm-controller
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: image-automation-controller
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: {{ .Values.resources.imageAutomationController.requests.cpu }}
        memory: {{ .Values.resources.imageAutomationController.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.resources.imageAutomationController.limits.cpu }}
        memory: {{ .Values.resources.imageAutomationController.limits.memory }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  image-automation-controller
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: image-reflector-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: {{ .Values.resources.imageReflectorController.requests.cpu }}
        memory: {{ .Values.resources.imageReflectorController.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.resources.imageReflectorController.limits.cpu }}
        memory: {{ .Values.resources.imageReflectorController.limits.memory }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: image-reflector-controller
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kustomize-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: {{ .Values.resources.kustomizeController.requests.cpu }}
        memory: {{ .Values.resources.kustomizeController.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.resources.kustomizeController.limits.cpu }}
        memory: {{ .Values.resources.kustomizeController.limits.memory }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kustomize-controller
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: notification-controller
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: {{ .Values.resources.notificationController.requests.cpu }}
        memory: {{ .Values.resources.notificationController.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.resources.notificationController.limits.cpu }}
        memory: {{ .Values.resources.notificationController.limits.memory }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-controller
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: source-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: manager
      controlledValues: RequestsAndLimits
      minAllowed:
        cpu: {{ .Values.resources.sourceController.requests.cpu }}
        memory: {{ .Values.resources.sourceController.requests.memory }}
      maxAllowed:
        cpu: {{ .Values.resources.sourceController.limits.cpu }}
        memory: {{ .Values.resources.sourceController.limits.memory }}
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: source-controller
  updatePolicy:
    updateMode: Auto
{{ end }}
