bases:
- ../../flux-app/customer
- ../../flux-app/giantswarm
- ../../flux-giantswarm-resources
replacements:
  # Points collection GitRepository to correct URL
  - source:
      kind: ConfigMap
      name: provider-data
      fieldPath: data.collection_url
    targets:
      - select:
          kind: GitRepository
          name: collection
          namespace: flux-giantswarm
        fieldPaths:
          - spec.url
resources:
- configmap-provider-data.yaml
