apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metrics-server-app
  namespace: org-sample
spec:
  interval: 5m
  provider: generic
  ref:
    tag: "2.8.0"
  url: oci://gsoci.azurecr.io/charts/giantswarm/metrics-server-app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sample-customer-metrics-server
  namespace: org-sample
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chartRef:
    kind: OCIRepository
    name: metrics-server-app
    namespace: org-sample
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    ## Empty value because the giantswarm-critical priority class is missing on EKS imported clusters
    priorityClassName: ""
    hostNetwork: true
