apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-customer-metrics-server
  namespace: org-sample
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chart:
    spec:
      chart: metrics-server-app
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: giantswarm-default-catalog
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    ## Empty value because the giantswarm-critical priority class is missing on EKS imported clusters
    priorityClassName: ""
    hostNetwork: true
