apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-giantswarm
spec:
  template:
    spec:
      initContainers:
      - args:
        - cp $(which helm) /helm-bin/helmV3 && chmod +x /helm-bin/helmV3
        command:
        - sh
        - -c
        image: gsoci.azurecr.io/giantswarm/alpine-helm:3.9.3
        imagePullPolicy: IfNotPresent
        name: ensure-helm
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 100
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /helm-bin
          name: helm-bin
      containers:
      - name: manager
        image: gsoci.azurecr.io/giantswarm/kustomize-controller:v1.2.2
        volumeMounts:
        - mountPath: /usr/bin/helmV3
          name: helm-bin
          subPath: helmV3
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ca-certs
        - mountPath: /etc/ssl/certs/
          name: ssl-certs
      volumes:
      - hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
          type: ""
        name: ca-certs
      - hostPath:
          path: /etc/ssl/certs/
          type: ""
        name: ssl-certs
      - name: helm-bin
        emptyDir: {}
