apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-vault-token
  namespace: flux-giantswarm
spec:
  # every 5 months; token TTL is 180 days
  schedule: "0 0 1 */5 *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - args:
              - --vault-address=$(VAULT_ADDR)
              - --vault-role=konfigure
              - --vault-token-secret-name=flux-vault-token
              - --vault-token-secret-namespace=flux-giantswarm
              env:
              - name: VAULT_ADDR
                valueFrom:
                  configMapKeyRef:
                    key: VAULT_ADDR
                    name: management-cluster-metadata
              image: gsoci.azurecr.io/giantswarm/k8s-jwt-to-vault-token:0.1.0
              imagePullPolicy: Always
              name: ensure-vault-token
          containers:
            - args:
                - delete
                - pods
                - --namespace=flux-giantswarm
                - -lapp=kustomize-controller
              image: gsoci.azurecr.io/giantswarm/docker-kubectl:1.18.8
              name: restart-kustomize-controller
          serviceAccountName: refresh-vault-token
          restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: refresh-vault-token
  namespace: flux-giantswarm
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: refresh-vault-token
  namespace: flux-giantswarm
subjects:
  - kind: ServiceAccount
    name: refresh-vault-token
    namespace: flux-giantswarm
roleRef:
  kind: Role
  name: refresh-vault-token
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: refresh-vault-token
  namespace: flux-giantswarm

