apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-crd-controller-giantswarm
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-controller-giantswarm
subjects:
- kind: ServiceAccount
  name: automation
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-giantswarm-automation
subjects:
  - kind: ServiceAccount
    name: automation
    namespace: flux-giantswarm
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: automation
  namespace: flux-giantswarm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-pods-and-logs
  namespace: flux-giantswarm
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-flux-logs-automation
  namespace: flux-giantswarm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-pods-and-logs
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: "automation"
  namespace: "default"
