---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.kyverno.io/aggregate-to-reports-controller: "true"
  name: kyverno:gs-mcb:flux-operator-multi-tenancy
rules:
  - apiGroups:
      - fluxcd.controlplane.io
    resources:
      - resourcesets
      - fluxinstances
    verbs:
      - get
      - list
      - watch
