apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-customer-promtail
  namespace: org-sample
spec:
  releaseName: promtail
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chart:
    spec:
      chart: promtail
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: giantswarm-catalog
        namespace: default
  interval: 50m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: sample-customer-promtail-config
      valuesKey: values
