apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: org-sample
spec:
  interval: 5m
  provider: generic
  ref:
    tag: "0.45.0"
  url: oci://gsoci.azurecr.io/charts/giantswarm/loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sample-customer-loki
  namespace: org-sample
spec:
  releaseName: loki
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chartRef:
    kind: OCIRepository
    name: loki
    namespace: org-sample
  interval: 50m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: sample-customer-loki-config
      valuesKey: values
