apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-customer-loki
  namespace: org-sample
spec:
  releaseName: loki
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chart:
    spec:
      chart: loki
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: giantswarm-catalog
        namespace: default
  interval: 50m
  install:
    remediation:
      retries: 3
