apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-customer-external-dns
  namespace: org-sample
spec:
  releaseName: external-dns
  targetNamespace: kube-system
  storageNamespace: kube-system
  kubeConfig:
    secretRef:
      name: sample-customer-kubeconfig
  chart:
    spec:
      chart: external-dns-app
      version: 2.42.0
      sourceRef:
        kind: HelmRepository
        name: giantswarm-catalog
        namespace: default
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    provider: aws
    aws:
      irsa: "true"
      batchChangeInterval: null
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::242036376510:role/sample-customer-Route53Manager-Role
    domainFilters:
      - sample-customer.gaws.giantswarm.io
    txtOwnerId: giantswarm-io-external-dns
    txtPrefix: sample-customer
    annotationFilter: giantswarm.io/external-dns=managed
    priorityClassName: ""
    sources:
      - service
    extraArgs:
      - "--aws-batch-change-interval=10s"
    global:
      podSecurityStandards:
        enforced: true
    crd:
      install: false
