name: "Silences validate"
description: "Validate silences CR files"
inputs:
  directory_pattern:
    description: "Bash pattern to match directories with silence CR files"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        make bin/yq
        make bin/kustomize
    - name: Check directory pattern
      shell: bash
      run: |
        # Check for non-empty pattern and valid directories
        test -n "${{ inputs.directory_pattern }}" && \
          echo ${{ inputs.directory_pattern }} | xargs -I{} test -d {} && echo ok
    - name: Validate silences files
      shell: bash
      run: |
        for directory in ${{ inputs.directory_pattern }}; do
          silences-validate.sh "$directory"
        done
    - name: Setup kind cluster
      uses: helm/kind-action@v1
    - name: Validate unique names
      shell: bash
      run: |
        # create CRD
        kubectl create -f https://raw.githubusercontent.com/giantswarm/silence-operator/master/config/crd/monitoring.giantswarm.io_silences.yaml
        for directory in ${{ inputs.directory_pattern }}; do
          kustomize build "$directory" --output "${directory}/resources.yaml"
          kubectl apply -f "${directory}/resources.yaml"
          kubectl delete -f "${directory}/resources.yaml"
        done
