name: "Silences validate"
description: "Validate silences CR files"
inputs:
  directory_pattern:
    description: "Bash pattern to match directories containing silence CR files"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Install dependencies
      shell: bash
      run: |
        make bin/yq
        make bin/kustomize
    - name: Check directory pattern
      shell: bash
      run: |
        # Check for non-empty pattern and valid directories
        test -n "${{ inputs.directory_pattern }}" && \
          printf "%s\n" ${{ inputs.directory_pattern }} | xargs -I{} test -d {} && echo ok
    - name: Validate silences files
      shell: bash
      run: |
        # Run files validation for each directory
        for directory in ${{ inputs.directory_pattern }}; do
          echo "Validating silence files in $directory"
          silences-validate.sh "$directory"
        done
    - name: Setup kind cluster
      uses: helm/kind-action@v1
    - name: Validate silence CRs
      shell: bash
      run: |
        # Run CR validation for each directory
        kubectl create -f https://raw.githubusercontent.com/giantswarm/silence-operator/master/config/crd/monitoring.giantswarm.io_silences.yaml
        for directory in ${{ inputs.directory_pattern }}; do
          echo "Validating silence CRs in $directory"
          kustomize build "$directory" --output "${directory}/resources.yaml"
          kubectl apply -f "${directory}/resources.yaml"
          kubectl delete -f "${directory}/resources.yaml"
        done
