# Github action used to validate silences CR files added to this repository.
# Using an action rather than a workflow to be able to pass different inputs depending where it is called from, since workflows do not support inputs for push events.
name: "Silences validate"
description: "Validate silences CR files"
inputs:
  directory_pattern:
    description: "Bash pattern to match directories containing silence CR files"
    required: true
runs:
  using: "composite"
  steps:
    # Set PATH to include GitHub Action path
    # This is needed to run the silences-validate.sh script
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    # Install dependencies
    # yq: is used by silences-validate.sh
    # kustomize: is used to validate silences CRs
    - name: Install dependencies
      shell: bash
      run: |
        make bin/yq
        make bin/kustomize
    # Check for non-empty directory_pattern and valid directories
    - name: Check directory pattern
      shell: bash
      run: |
        shopt -s globstar
        test -n "${{ inputs.directory_pattern }}" && \
          printf "%s\n" ${{ inputs.directory_pattern }} | xargs -I{} test -d {} && echo ok
    # Run files validation for each directory
    - name: Validate silences files
      shell: bash
      run: |
        shopt -s globstar
        for directory in ${{ inputs.directory_pattern }}; do
          echo "Validating silences files in $directory"
          silences-validate.sh "$directory"
        done
    - name: Setup kind cluster
      uses: helm/kind-action@v1
    # Run CR validation for each directory
    - name: Validate silences CRs
      shell: bash
      run: |
        shopt -s globstar
        kubectl create -f https://raw.githubusercontent.com/giantswarm/silence-operator/master/config/crd/bases/monitoring.giantswarm.io_silences.yaml
        for directory in ${{ inputs.directory_pattern }}; do
          echo "Validating silences CRs in $directory"
          kustomize build "$directory" --output "${directory}/resources.yaml"
          test -s "${directory}/resources.yaml" || continue
          kubectl apply -f "${directory}/resources.yaml"
          kubectl delete -f "${directory}/resources.yaml"
        done
