apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zot
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: zot
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: giantswarm-catalog
        namespace: flux-giantswarm
      version: 2.3.0
  install:
    remediation:
      retries: 10
      remediateLastFailure: false
  interval: 1m
  targetNamespace: zot
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: false
  valuesFrom:
    - kind: ConfigMap
      name: zot-cache-values
      valuesKey: values.yaml
