patches:
  - target:
      labelSelector: giantswarm.io/kustomize-selector=remove-psp
    patch: |
      $patch: delete
      apiVersion: policy/v1beta1
      kind: PodSecurityPolicy
      metadata:
        name: DOES NOT MATTER
  - target:
      labelSelector: giantswarm.io/kustomize-selector=remove-psp
    patch: |
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: DOES NOT MATTER
  - target:
      labelSelector: giantswarm.io/kustomize-selector=remove-psp
    patch: |
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: DOES NOT MATTER
