---
apiVersion: konfigure.giantswarm.io/v1alpha1
kind: Konfiguration
metadata:
  name: muster-konfiguration
  namespace: flux-giantswarm
spec:
  targets:
    schema:
      reference:
        name: management-cluster-configuration
        namespace: giantswarm
    defaults:
      variables:
        - name: installation
          value: "${cluster_name}"
    iterations:
      muster:
        variables:
          - name: app
            value: muster
  destination:
    namespace: flux-giantswarm
    naming:
      suffix: konfiguration
  reconciliation:
    interval: 1m
    retryInterval: 10s
    suspend: false
  sources:
    flux:
      gitRepository:
        name: "giantswarm-config"
        namespace: "flux-giantswarm"

