apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: muster-valkey
  namespace: flux-giantswarm
spec:
  interval: 10m
  url: oci://gsoci.azurecr.io/charts/giantswarm/valkey
  ref:
    semver: ">=0.0.0"
  provider: generic

