apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: collection
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: github-giantswarm-https-credentials
  timeout: 5m
  url: "{replaced in bases/provider/<PROVIDER>/kustomization.yaml}"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: management-clusters-fleet
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-giantswarm-https-credentials
  timeout: 60s
  url: https://github.com/giantswarm/management-clusters-fleet
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: giantswarm-config
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-giantswarm-https-credentials
  timeout: 60s
  url: https://github.com/giantswarm/config
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: shared-configs
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: shared-configs-ssh-credentials
  timeout: 60s
  url: ssh://git@ssh.github.com:${github_port}/giantswarm/shared-configs
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: giantswarm-configs-new
  namespace: flux-giantswarm
spec:
  include:
    - repository:
        name: shared-configs
      fromPath: default
      toPath: default
    - repository:
        name: shared-configs
      fromPath: include
      toPath: include
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: configs-ssh-credentials
  timeout: 60s
  url: ssh://git@ssh.github.com:${github_port}/giantswarm/${customer_codename}-configs.git
