apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: collection
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: master
  secretRef:
    name: github-giantswarm-https-credentials
  timeout: 5m
  url: "{replaced in bases/provider/<PROVIDER>/kustomization.yaml}"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: management-clusters-fleet
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: flux-2
  secretRef:
    name: github-giantswarm-https-credentials
  timeout: 60s
  url: https://github.com/giantswarm/management-clusters-fleet
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: giantswarm-config
  namespace: flux-giantswarm
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-giantswarm-https-credentials
  timeout: 60s
  url: https://github.com/giantswarm/config
