apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
  namespace: flux-giantswarm
  labels:
    backstage.io/kubernetes-id: backstage
spec:
  chartRef:
    kind: OCIRepository
    name: backstage
    namespace: flux-giantswarm
  install:
    remediation:
      retries: 10
      remediateLastFailure: false
  interval: 1m
  targetNamespace: backstage
  timeout: 10m
  upgrade:
    remediation:
      retries: 10
      remediateLastFailure: false
