apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config-backstage
  namespace: flux-giantswarm
data:
  values: |
    sharedConfig: |
      adminGroups:
        - giantswarm-ad:giantswarm-admins
        - giantswarm-github:giantswarm:giantswarm-admins

      clusterDetailsResources:
        overviewDashboard:
          label: "Cluster overview \n dashboard"
          icon: GrafanaIcon
          url: "https://grafana.$${{BASE_DOMAIN}}/d/gs_cluster-overview/cluster-overview?orgId=1&from=now-6h&to=now&timezone=browser&var-datasource=default&var-cluster=$${{CLUSTER_NAME}}"
        alertsDashboard:
          label: Alerts
          icon: NotificationsNone
          url: "https://grafana.$${{BASE_DOMAIN}}/alerting?orgId=2"
        webUIWC:
          label: Web UI
          icon: Public
          url: "https://happa.$${{BASE_DOMAIN}}/organizations/$${{ORG_NAME}}/clusters/$${{CLUSTER_NAME}}"
          clusterType: workload
        webUIMC:
          label: Web UI
          icon: Public
          url: "https://happa.$${{BASE_DOMAIN}}"
          clusterType: management

      homepageResources:
        gsDocs:
          label: "Giant Swarm \n Docs"
          icon: MenuBook
          url: "https://docs.giantswarm.io"
        gsGitHub:
          label: "Giant Swarm \n GitHub"
          icon: GitHub
          url: "https://github.com/giantswarm"
        portalChangelog:
          label: "Portal \n changelog"
          icon: BackstageIcon
          url: "https://github.com/giantswarm/backstage/releases"
        portalRoadmap:
          label: "Portal \n roadmap"
          icon: BackstageIcon
          url: "https://github.com/orgs/giantswarm/projects/273/views/28?filterQuery=-status%3A%22Done+%E2%9C%85%22+kind%3A%22Epic+%F0%9F%8E%AF%22%2C%22Rock+%F0%9F%AA%A8%22%2C%22Feature+%F0%9F%92%AB%22+label%3Aui%2Fbackstage"

      # Source: https://kubernetes.io/releases/
      kubernetesVersions:
        "1.20":
          minorVersion: "1.20"
          eolDate: 2021-12-30
        "1.21":
          minorVersion: "1.21"
          eolDate: 2022-06-28
        "1.22":
          minorVersion: "1.22"
          eolDate: 2022-10-28
        "1.23":
          minorVersion: "1.23"
          eolDate: 2023-02-28
        "1.24":
          minorVersion: "1.24"
          eolDate: 2023-07-28
        "1.25":
          minorVersion: "1.25"
          eolDate: 2023-10-28
        "1.26":
          minorVersion: "1.26"
          eolDate: 2024-02-28
        "1.27":
          minorVersion: "1.27"
          eolDate: 2024-06-28
        "1.28":
          minorVersion: "1.28"
          eolDate: 2024-10-28
        "1.29":
          minorVersion: "1.29"
          eolDate: 2025-02-28
        "1.30":
          minorVersion: "1.30"
          eolDate: 2025-06-28
        "1.31":
          minorVersion: "1.31"
          eolDate: 2025-10-28
        "1.32":
          minorVersion: "1.32"
          eolDate: 2026-02-28
        "1.33":
          minorVersion: "1.33"
          eolDate: 2026-06-28
