apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config-backstage
  namespace: flux-giantswarm
data:
  values: |
    sharedConfig: |
      adminGroups:
        - giantswarm-ad:giantswarm-admins
        - giantswarm-github:giantswarm:giantswarm-admins

      # Source: https://kubernetes.io/releases/
      kubernetesVersions:
        "1.20":
          minorVersion: "1.20"
          eolDate: 2021-12-30
        "1.21":
          minorVersion: "1.21"
          eolDate: 2022-06-28
        "1.22":
          minorVersion: "1.22"
          eolDate: 2022-10-28
        "1.23":
          minorVersion: "1.23"
          eolDate: 2023-02-28
        "1.24":
          minorVersion: "1.24"
          eolDate: 2023-07-28
        "1.25":
          minorVersion: "1.25"
          eolDate: 2023-10-28
        "1.26":
          minorVersion: "1.26"
          eolDate: 2024-02-28
        "1.27":
          minorVersion: "1.27"
          eolDate: 2024-06-28
        "1.28":
          minorVersion: "1.28"
          eolDate: 2024-10-28
        "1.29":
          minorVersion: "1.29"
          eolDate: 2025-02-28
        "1.30":
          minorVersion: "1.30"
          eolDate: 2025-06-28
        "1.31":
          minorVersion: "1.31"
          eolDate: 2025-10-28
        "1.32":
          minorVersion: "1.32"
          eolDate: 2026-02-28
