apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: giantswarm-kustomize-controller
  namespace: giantswarm
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - flux-giantswarm
        names:
        - 'kustomize-controller*'
