name: Validate silences

on:
  pull_request:
    paths:
      - '**.yaml'

jobs:
  silences_validate:
    runs-on: ubuntu-latest
    name: Validate silences
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # Fetch all history so silences-validate.sh can find changed files.
          fetch-depth: 0
      - uses: ./.github/actions/silences-validate
        with:
          directory_pattern: 'bases/silences'
