name: Report expired silences

on:
  schedule:
    # Everyday at 09:00
    - cron:  '0 9 * * *'
  workflow_dispatch:

jobs:
  silences_report_expired:
    runs-on: ubuntu-latest
    name: Report expired silences
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/silences-report-expired
        with:
          directory_pattern: 'bases/silences'
