name: Validate file names
on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  validate:
    uses: giantswarm/github-workflows/.github/workflows/validate-file-names.yaml@7a3c79b112a67c1e5a0e90e8c64207bff580152e # main
