apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
  - https://github.com/giantswarm/dev-platform-kratix-promises/raw/v0.1.0/github-template-repo-promise/promise.yaml
  - https://github.com/giantswarm/dev-platform-kratix-promises/raw/v0.1.0/app-deployment-promise/promise.yaml
